### ISSUE TITLE
Segmentation fault

### ISSUE THREAD

**Issue by LeaderSayo** [docker-scripts/dev--jekyll#6]
hello sir 
I keep getting Segmentation fault during `ds create` command.
can you review my code and point out where i am doing mistakes.
Sorry for absence as i mention in GSoC google form, i was busy in practical exams.
From now i am regular to this project.
One more thing can i also make freedombox container?

**Comment by dashohoxha** [comment]
> I keep getting Segmentation fault during ds create command.
can you review my code and point out where i am doing mistakes.

Your mistakes are on the code of the command `ds create`.

> One more thing can i also make freedombox container?

You are welcome to help with it, but what would you like to improve?

**Comment by LeaderSayo** [comment]
>You are welcome to help with it, but what would you like to improve?

Adding test scripts and rework on its code to learn better about containerization. 
And about error i try but i can't find any solution. can you please have a look at following code, it will be very helpful for me.

```
cmd_create_help() {
    cat <<_EOF
    create
        Create the container '$CONTAINER'.
_EOF
}
rename_function cmd_create ds_cmd_create
cmd_create() {
    mkdir -p  var-data/jekyll
    ds_cmd_create \
	--mount type=bind,src=$(pwd)/var-data,dst=/var \
	--workdir /var/jekyll 
	
}
```
Note: i change my github-username to LeaderSayo

**Comment by dashohoxha** [comment]
If you want to learn more about docker-scripts, please follow the instructions here: https://github.com/docker-scripts/ds/wiki

The documentation of docker-scripts is not complete, so it is important that you test and study the code of the existing applications (item 4) in order to comprehend more details about its features and its proper usage. It may take a few days to study all of them, but that's ok.

**Comment by LeaderSayo** [comment]
I am using `ds create` at `/opt/docker-scripts/jekyll` which cause a infinite loop.
Proper way is `ds @container create`.
Sorry for this silly issue.
